services:
  app:
    mem_limit: 115g
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    tty: true
    volumes:
      - ./docker_models_cache/.insightface/:/root/.insightface/ 
      - ./models/:/app/models/
      - /mnt/overflow/training-data/data:/app/data
      - ./src:/app/src
      - ./ai-agent-workspace/:/app/ai-agent-workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: "host"
    ports:
        - "5000:5000"
    env_file:
     - ./.env
    
    entrypoint: bash -c "cd /app/src/ && python3 gradio_app.py"
